apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-app
  name: dso-demo-dev
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-app
  type: ClusterIP
